version: '3'

services:
  ndc_ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    command: /ndc/docker/run_in_docker.sh
    working_dir: /ndc
    environment:
      NDC_IMAGE_NAME: "ubuntu_20_04"
      NDC_CONF_FILE: "/ndc/config/ndc.conf"
    ports:
      - 1337:1337
    volumes:
      - ../:/ndc
